# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: æ–°é—»ä¸­å¿ƒç®¡ç†ç³»ç»ŸåŠ¨æ€ç½‘
email: zning@sdust.edu.cn
description: > # this means to ignore newlines until "baseurl:"
æ„Ÿè°¢ä½¿ç”¨æœ¬ç³»ç»Ÿï¼Œæœ¬ç³»ç»Ÿç”±å±±ä¸œç§‘æŠ€å¤§å­¦ä¿¡æ¯ç§‘å­¦ä¸å·¥ç¨‹å­¦é™¢æ–°é—»ä¸­å¿ƒå¼€å‘ï¼Œä¸»è¦ç”¨äºæˆ‘é™¢æ–°é—»å‘å¸ƒã€æ›´æ–°åŠç»Ÿè®¡å·¥ä½œä¸é™¢æ–°é—»ä¸­å¿ƒå†…éƒ¨åŠå…¬ã€‚æœ¬ç³»ç»Ÿæ˜¯V0.1 Demoç‰ˆæœ¬ï¼Œå¦‚æœ‰ç³»ç»Ÿé—®é¢˜è¯·åŠæ—¶è”ç³»ç³»ç»Ÿç®¡ç†å‘˜åŠå¼€å‘è€…ï¼šEmail: zning@sdust.edu.cn Tel: +8613687671402 è¿™ä¸ªç³»ç»Ÿå®‰å…¨æ€§ä¸é«˜ï¼Œå„ä½æœ‰ä»€ä¹ˆå»ºè®®å¯ä»¥forkäº†ç©ä¸€ç©ï¼Œæ¬¢è¿å¤§ç‰›æ‰“è„¸ğŸ˜„ã€‚
baseurl: "/newscentersystem" # the subpath of your site, e.g. /blog
url: "http://zning.me" # the base hostname & protocol for your site
twitter_username: z_ning
github_username:  zning1994

# Build settings
markdown: kramdown
